name: Quality Control & Publish CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: '**'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: install
        run: npm ci
      - name: testing
        run: npm run jest && npm run cypress

  publish-package:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/main' }}

    needs: [quality-check]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: install
        run: npm ci
      - name: bundle
        run: npm run rollup
      - name: publish
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
